runtime: php55
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /
  script: /pages/main.php

- url: /main
  script: /pages/main.php

- url: /colors
  script: /pages/colors.php

- url: /stats
  script: /pages/stats.php

- url: /wait
  script: /pages/wait.php

- url: /timeout
  script: /pages/timeout.php

- url: /red
  script: /colors/red.php

- url: /green
  script: /colors/green.php

- url: /blue
  script: /colors/blue.php

- url: /cyan
  script: /colors/cyan.php

- url: /magenta
  script: /colors/magenta.php

- url: /yellow
  script: /colors/yellow.php

- url: /reset
  script: reset.php
  login: admin